#:kivy 1.0.9

<BeerGauge>:
    ToolBar:
        progressBar: progBar
        orientation: 'tb-lr'

        BGButton:
            text: 'Beer'

        BGButton:
            text: 'Wine'

        BGButton:
            text: 'Whisky'

        BGButton:
            text: 'Other'

    BeerGaugeBar:
        id: progBar
        center_y: root.height * .7
        width: root.width


<BGButton>:
    on_press: root.do_action()
